'use server';

/**
 * @fileOverview Provides AI-powered reframes for negative thoughts.
 *
 * - reframeThought - A function that takes a negative thought as input and returns validating reframes.
 * - ReframeThoughtInput - The input type for the reframeThought function.
 * - ReframeThoughtOutput - The return type for the reframeThought function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ReframeThoughtInputSchema = z.object({
  negativeThought: z
    .string()
    .describe('The negative thought that needs reframing.'),
});
export type ReframeThoughtInput = z.infer<typeof ReframeThoughtInputSchema>;

const ReframeThoughtOutputSchema = z.object({
  reframedThought: z
    .string()
    .describe('The reframed, more positive thought generated by AI.'),
});
export type ReframeThoughtOutput = z.infer<typeof ReframeThoughtOutputSchema>;

export async function reframeThought(input: ReframeThoughtInput): Promise<ReframeThoughtOutput> {
  return reframeThoughtFlow(input);
}

const prompt = ai.definePrompt({
  name: 'reframeThoughtPrompt',
  input: {schema: ReframeThoughtInputSchema},
  output: {schema: ReframeThoughtOutputSchema},
  prompt: `You are a helpful AI assistant designed to provide validating and positive reframes for negative thoughts.

  Please reframe the following negative thought into a more positive and validating perspective:

  Negative Thought: {{{negativeThought}}}

  Reframed Thought: `,
});

const reframeThoughtFlow = ai.defineFlow(
  {
    name: 'reframeThoughtFlow',
    inputSchema: ReframeThoughtInputSchema,
    outputSchema: ReframeThoughtOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
